swagger: '2.0'
info:
  title: EMS Rest APIs using Cloud Endpoints + GCF
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: ems-rest-api-ai2wkuneha-uc.a.run.app
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-central1-rest-api-391313.cloudfunctions.net/getAllEmp
        protocol: h2
      responses:
        '200':
          description: A successful response
          schema:
            type: string