basePath: /api/v1
definitions:
  structure.Employee:
    properties:
      date_of_birth:
        type: string
      department:
        type: string
      email:
        type: string
      id:
        type: integer
      is_admin:
        type: boolean
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role:
        type: string
    type: object
  structure.ShowEmployee:
    properties:
      date_of_birth:
        type: string
      department:
        type: string
      email:
        type: string
      id:
        type: integer
      is_admin:
        type: boolean
      name:
        type: string
      phone_number:
        type: string
      role:
        type: string
    type: object
  views.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  views.SuccessResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: kalra.udit15@gmail.com
    name: Udit Kalra
    url: https://github.com/Udit-Kalra-1117
  description: This is the implementation and documentation of the Employee Management
    System API in Go using Swagger
  title: Implementing and Documenting Employee Management System API in Go using Swagger
  version: "1"
paths:
  /api/v1/employees:
    get:
      description: Get a list of all employees
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/structure.ShowEmployee'
            type: array
      summary: Get all employees
      tags:
      - Employees
    post:
      consumes:
      - application/json
      description: Create a new employee with the provided details
      parameters:
      - description: Employee details
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/structure.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structure.ShowEmployee'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Create a new employee
      tags:
      - Employees
  /api/v1/employees/{id}:
    delete:
      description: Delete an employee with the provided ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Delete an employee by ID
      tags:
      - Employees
    get:
      description: Get an employee with the provided ID
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structure.ShowEmployee'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Get an employee by ID
      tags:
      - Employees
    put:
      consumes:
      - application/json
      description: Update an existing employee with the provided ID and details
      parameters:
      - description: Employee ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated employee details
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/structure.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structure.ShowEmployee'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/views.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/views.ErrorResponse'
      summary: Update an existing employee
      tags:
      - Employees
securityDefinitions:
  bearerToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
